# Book settings
title: APEX Stats
author: David Schuster
logo: logo.png  # Relative path to the logo inside the jupyter_book folder

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file for citations
bibtex_bibfiles:
  - references.bib  # Relative path to the bibtex file inside the jupyter_book folder

# Repository settings
repository:
  url: https://github.com/michellebacareinke/jupyter-book  # GitHub repository URL
  path_to_book: "jupyter_book"  # Path to book folder
  branch: main  # Branch for deployment

# GitHub buttons for issues and repository
html:
  use_issues_button: true
  use_repository_button: true

# URL settings for Netlify (optional for custom domain)
url: "https://apexstats.netlify.app"  # Netlify URL
baseurl: ""  # Custom domain
