# Book settings
title: APEX Stats
author: David Schuster
logo: logo.png  # Path to logo in jupyter_book folder

# Notebook execution (can change to force w/ no quotes)
execute:
  execute_notebooks: "off"

# Define name of latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add bibtex file for citations
bibtex_bibfiles:
  - references.bib  # Path to bibtex file in jupyter_book folder

# Repository settings
repository:
  url: https://github.com/michellebacareinke/jupyter-book  # GitHub repository URL
  path_to_book: "jupyter_book"  # Path to book folder
  branch: main  # Branch for deployment

# GitHub buttons for issues and repository
html:
  use_issues_button: true
  use_repository_button: true

# URL settings for Netlify (optional for custom domain)
url: "https://apexstats.netlify.app"  # Netlify URL
baseurl: ""  # Custom domain

launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org
